[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build_windows]
command = "cargo"
args = ["build", "--target=x86_64-pc-windows-gnu", "--release"]

[tasks.build_linux]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.my-flow]
dependencies = [
    "format",
    "build_windows",
    "build_linux",
    "test"
]