[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build_windows]
command = "cargo"
args = ["build", "--target=x86_64-pc-windows-gnu", "--release"]

[tasks.build_linux]
command = "cargo"
args = ["build", "--release"]

[tasks.mkdir]
command = "mkdir"
args = ["-p", "target/build/assets"]

[tasks.copy_assets]
command = "cp"
args = ["-rp", "assets/", "target/build/assets/"]

[tasks.copy_binary_linux]
command = "cp"
args = ["target/release/bevy-test", "target/build/assets/bevy-test"]

[tasks.copy_binary_windows]
command = "cp"
args = ["target/x86_64-pc-windows-gnu/release/bevy-test.exe", "target/build/assets/bevy-test.exe"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.build]
dependencies = [
    "format",
    "build_windows",
    "mkdir",
    "copy_assets",
    "copy_binary_linux",
    "copy_binary_windows",
    "test"
]